services:
  db:
    image: mysql:8.4.3
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    environment:
      DB_HOST: db  
    depends_on:
      - db
    volumes:
      - ./env_volume:/app/env
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
    environment:
      NEXT_PUBLIC_HOST: http://localhost
      NEXT_PUBLIC_PORT: 80
    depends_on:
      - backend
    volumes:
      - ./env_volume:/app/env


  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  db_data:
  
