name: Imagen a dockerHub

on:
    [workflow_dispatch]

jobs:
    publish_images:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: build
              run: docker build ./backend/ -t angelsalgadom/backend:latest
            - name: push
              run: docker push angelsalgadom/backend:latest
